### ISSUE TITLE
Using array_key_exists() on objects is deprecated when using paginate() with object target

### ISSUE THREAD

**Issue by ThauEx** [KnpLabs/knp-components#294]
When using the `paginate()` method of the `Paginator` class with an object as target, it throws the following deprecation:
> array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in vendor/knplabs/knp-components/src/Knp/Component/Pager/Pagination/AbstractPagination.php line 163

It can be fixed with the following change:
```diff
    public function offsetExists($offset): bool
    {
        if ($this->items instanceof \ArrayIterator) {
            return array_key_exists($offset, iterator_to_array($this->items));
        }

-        return array_key_exists($offset, $this->items);
+        return isset($this->items[$offset]);
    }
```

Since `paginate` has the following description for the `$target` argument: 
> * @param mixed $target  anything what needs to be paginated
I would say this is a bug.

Should I open a PR for that?

**Comment by garak** [comment]
Can you provide an example of using paginate with an object?

**Comment by ThauEx** [comment]
I don't have any sample code, but it could be something like `ArrayCollection` from the doctrine collections.

**Comment by garak** [comment]
That's already working, as it's working with QueryBuilder objects and with many other objects.

**Comment by ThauEx** [comment]
I know that it works with `ArrayCollection`, but php 7.4 deprecated using `array_key_exists` on objects. This is the reason, why I opened this issue.
Together with the KnpPaginatorBundle  and Twig,  `offsetExists` gets called somewhere and triggers the mentioned deprecation message.

**Comment by garak** [comment]
A PR is welcome

**Comment by ThauEx** [comment]
Done 🙂

**Comment by W0rma** [comment]
@garak The linked PR was closed more than one year ago with the following remark:

> I'm closing this since we don't support PHP 7.4 anymore

Should this issue be closed as well?

**Comment by garak** [comment]
I'm not really sure.
In theory, it could be still a problem if someone would use the paginator with a custom object not implementing ArrayIterator.
We still have an inconsistency here.

**Comment by garak** [comment]
Maybe we can try this:
```php
$items = get_mangled_object_vars($this->items);

return array_key_exists($offset, $items);
```
A PR is still welcome
